/**
 * Code by Xipzer
 */

import { Network } from '../types'
import { clusterApiUrl } from '@solana/web3.js'
import { useSettingsStore } from '../store/settingsStore'

export type { Network }

const ENV_ALCHEMY_KEY = import.meta.env.VITE_ALCHEMY_API_KEY || ''
const ENV_HELIUS_KEY = import.meta.env.VITE_HELIUS_API_KEY || ''

export function getAlchemyApiKey(): string {
  return useSettingsStore.getState().alchemyApiKey || ENV_ALCHEMY_KEY
}

export function getHeliusApiKey(): string {
  return useSettingsStore.getState().heliusApiKey || ENV_HELIUS_KEY
}

function alchemyUrl(network: string): string {
  return `https://${network}.g.alchemy.com/v2/${ENV_ALCHEMY_KEY}`
}

export const EVM_NETWORKS: Network[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    chainId: 1,
    rpcUrl: 'https://ethereum-rpc.publicnode.com',
    alchemyRpcUrl: alchemyUrl('eth-mainnet'),
    symbol: 'ETH',
    explorerUrl: 'https://etherscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_ethereum.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'base',
    name: 'Base',
    chainId: 8453,
    rpcUrl: 'https://mainnet.base.org',
    alchemyRpcUrl: alchemyUrl('base-mainnet'),
    symbol: 'ETH',
    explorerUrl: 'https://basescan.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_base.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    chainId: 56,
    rpcUrl: 'https://bsc-dataseed1.binance.org',
    alchemyRpcUrl: alchemyUrl('bnb-mainnet'),
    symbol: 'BNB',
    explorerUrl: 'https://bscscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_binance.jpg',
    nativeCurrency: { name: 'Binance Coin', symbol: 'BNB', decimals: 18 },
  },
  {
    id: 'polygon',
    name: 'Polygon',
    chainId: 137,
    rpcUrl: 'https://polygon-bor-rpc.publicnode.com',
    alchemyRpcUrl: alchemyUrl('polygon-mainnet'),
    symbol: 'POL',
    explorerUrl: 'https://polygonscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_polygon.jpg',
    nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    chainId: 42161,
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    alchemyRpcUrl: alchemyUrl('arb-mainnet'),
    symbol: 'ETH',
    explorerUrl: 'https://arbiscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_arbitrum.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'optimism',
    name: 'Optimism',
    chainId: 10,
    rpcUrl: 'https://mainnet.optimism.io',
    alchemyRpcUrl: alchemyUrl('opt-mainnet'),
    symbol: 'ETH',
    explorerUrl: 'https://optimistic.etherscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_optimism.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    chainId: 43114,
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    symbol: 'AVAX',
    explorerUrl: 'https://snowtrace.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_avalanche.jpg',
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
  },
  {
    id: '0g',
    name: '0G',
    chainId: 16661,
    rpcUrl: 'https://evmrpc.0g.ai',
    symbol: '0G',
    explorerUrl: 'https://chainscan.0g.ai',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_0g.jpg',
    nativeCurrency: { name: '0G', symbol: '0G', decimals: 18 },
  },
  {
    id: 'abstract',
    name: 'Abstract',
    chainId: 2741,
    rpcUrl: 'https://api.mainnet.abs.xyz',
    symbol: 'ETH',
    explorerUrl: 'https://abscan.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_abstract.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'apechain',
    name: 'ApeChain',
    chainId: 33139,
    rpcUrl: 'https://rpc.apechain.com',
    symbol: 'APE',
    explorerUrl: 'https://apescan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_apechain.jpg',
    nativeCurrency: { name: 'ApeCoin', symbol: 'APE', decimals: 18 },
  },
  {
    id: 'b2',
    name: 'B²',
    chainId: 223,
    rpcUrl: 'https://rpc.bsquared.network',
    symbol: 'BTC',
    explorerUrl: 'https://explorer.bsquared.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_bsquared.jpg',
    nativeCurrency: { name: 'Bitcoin', symbol: 'BTC', decimals: 18 },
  },
  {
    id: 'berachain',
    name: 'Berachain',
    chainId: 80094,
    rpcUrl: 'https://rpc.berachain.com',
    symbol: 'BERA',
    explorerUrl: 'https://berascan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_berachain.jpg',
    nativeCurrency: { name: 'BERA', symbol: 'BERA', decimals: 18 },
  },
  {
    id: 'bitlayer',
    name: 'Bitlayer',
    chainId: 200901,
    rpcUrl: 'https://rpc.bitlayer.org',
    symbol: 'BTC',
    explorerUrl: 'https://www.btrscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_bitlayer.jpg',
    nativeCurrency: { name: 'Bitcoin', symbol: 'BTC', decimals: 18 },
  },
  {
    id: 'blast',
    name: 'Blast',
    chainId: 81457,
    rpcUrl: 'https://rpc.blast.io',
    symbol: 'ETH',
    explorerUrl: 'https://blastscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_blast.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'bob',
    name: 'BOB',
    chainId: 60808,
    rpcUrl: 'https://rpc.gobob.xyz',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.gobob.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_bob.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'bouncebit',
    name: 'BounceBit',
    chainId: 6001,
    rpcUrl: 'https://fullnode-mainnet.bouncebitapi.com',
    symbol: 'BB',
    explorerUrl: 'https://bbscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_bouncebit.jpg',
    nativeCurrency: { name: 'BounceBit', symbol: 'BB', decimals: 18 },
  },
  {
    id: 'celo',
    name: 'Celo',
    chainId: 42220,
    rpcUrl: 'https://forno.celo.org',
    symbol: 'CELO',
    explorerUrl: 'https://celoscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_celo.jpg',
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
  },
  {
    id: 'chiliz',
    name: 'Chiliz',
    chainId: 88888,
    rpcUrl: 'https://rpc.chiliz.com',
    symbol: 'CHZ',
    explorerUrl: 'https://chiliscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_chiliz.jpg',
    nativeCurrency: { name: 'Chiliz', symbol: 'CHZ', decimals: 18 },
  },
  {
    id: 'citrea',
    name: 'Citrea',
    chainId: 4114,
    rpcUrl: 'https://rpc.mainnet.citrea.xyz',
    symbol: 'cBTC',
    explorerUrl: 'https://explorer.mainnet.citrea.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_citrea.jpg',
    nativeCurrency: { name: 'Citrea Bitcoin', symbol: 'cBTC', decimals: 18 },
  },
  {
    id: 'conflux',
    name: 'Conflux eSpace',
    chainId: 1030,
    rpcUrl: 'https://evm.confluxrpc.com',
    symbol: 'CFX',
    explorerUrl: 'https://evm.confluxscan.net',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_conflux.jpg',
    nativeCurrency: { name: 'Conflux', symbol: 'CFX', decimals: 18 },
  },
  {
    id: 'core',
    name: 'CORE',
    chainId: 1116,
    rpcUrl: 'https://rpc.coredao.org',
    symbol: 'CORE',
    explorerUrl: 'https://scan.coredao.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_core.jpg',
    nativeCurrency: { name: 'Core', symbol: 'CORE', decimals: 18 },
  },
  {
    id: 'cronos',
    name: 'Cronos',
    chainId: 25,
    rpcUrl: 'https://evm.cronos.org',
    symbol: 'CRO',
    explorerUrl: 'https://explorer.cronos.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_cronos.jpg',
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
  },
  {
    id: 'cronos-zkevm',
    name: 'Cronos zkEVM',
    chainId: 388,
    rpcUrl: 'https://mainnet.zkevm.cronos.org',
    symbol: 'zkCRO',
    explorerUrl: 'https://explorer.zkevm.cronos.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_cronos%20zkevm.jpg',
    nativeCurrency: { name: 'Cronos zkEVM CRO', symbol: 'zkCRO', decimals: 18 },
  },
  {
    id: 'cyber',
    name: 'Cyber',
    chainId: 7560,
    rpcUrl: 'https://cyber.alt.technology',
    symbol: 'ETH',
    explorerUrl: 'https://cyberscan.co',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_cyber.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'data-network',
    name: 'DATA Network',
    chainId: 1514,
    rpcUrl: 'https://mainnet.storyrpc.io',
    symbol: 'DATA',
    explorerUrl: 'https://www.datanetscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_story.jpg',
    nativeCurrency: { name: 'DATA', symbol: 'DATA', decimals: 18 },
  },
  {
    id: 'dbk-chain',
    name: 'DBK Chain',
    chainId: 20240603,
    rpcUrl: 'https://rpc.mainnet.dbkchain.io',
    symbol: 'ETH',
    explorerUrl: 'https://scan.dbkchain.io',
    type: 'EVM',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'etherlink',
    name: 'Etherlink',
    chainId: 42793,
    rpcUrl: 'https://node.mainnet.etherlink.com',
    symbol: 'XTZ',
    explorerUrl: 'https://explorer.etherlink.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_etherlink.jpg',
    nativeCurrency: { name: 'Tezos', symbol: 'XTZ', decimals: 18 },
  },
  {
    id: 'fantom',
    name: 'Fantom',
    chainId: 250,
    rpcUrl: 'https://rpcapi.fantom.network',
    symbol: 'FTM',
    explorerUrl: 'https://ftmscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_fantom.jpg',
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
  },
  {
    id: 'flare',
    name: 'Flare',
    chainId: 14,
    rpcUrl: 'https://flare-api.flare.network/ext/C/rpc',
    symbol: 'FLR',
    explorerUrl: 'https://flarescan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_flare.jpg',
    nativeCurrency: { name: 'Flare', symbol: 'FLR', decimals: 18 },
  },
  {
    id: 'fraxtal',
    name: 'Fraxtal',
    chainId: 252,
    rpcUrl: 'https://rpc.frax.com',
    symbol: 'FRAX',
    explorerUrl: 'https://fraxscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_fraxtal.jpg',
    nativeCurrency: { name: 'Frax', symbol: 'FRAX', decimals: 18 },
  },
  {
    id: 'fuse',
    name: 'Fuse',
    chainId: 122,
    rpcUrl: 'https://rpc.fuse.io',
    symbol: 'FUSE',
    explorerUrl: 'https://explorer.fuse.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_fuse.jpg',
    nativeCurrency: { name: 'Fuse', symbol: 'FUSE', decimals: 18 },
  },
  {
    id: 'gnosis',
    name: 'Gnosis Chain',
    chainId: 100,
    rpcUrl: 'https://rpc.gnosischain.com',
    symbol: 'xDAI',
    explorerUrl: 'https://gnosisscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_xdai.jpg',
    nativeCurrency: { name: 'xDAI', symbol: 'xDAI', decimals: 18 },
  },
  {
    id: 'gravity',
    name: 'Gravity',
    chainId: 1625,
    rpcUrl: 'https://rpc.gravity.xyz',
    symbol: 'G',
    explorerUrl: 'https://explorer.gravity.xyz',
    type: 'EVM',
    nativeCurrency: { name: 'Gravity', symbol: 'G', decimals: 18 },
  },
  {
    id: 'hashkey',
    name: 'HashKey',
    chainId: 177,
    rpcUrl: 'https://mainnet.hsk.xyz',
    symbol: 'HSK',
    explorerUrl: 'https://hashkey.blockscout.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_hashkey%20chain.jpg',
    nativeCurrency: { name: 'HashKey', symbol: 'HSK', decimals: 18 },
  },
  {
    id: 'hemi',
    name: 'Hemi',
    chainId: 43111,
    rpcUrl: 'https://rpc.hemi.network/rpc',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.hemi.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_hemi.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'hyperevm',
    name: 'HyperEVM',
    chainId: 999,
    rpcUrl: 'https://rpc.hyperliquid.xyz/evm',
    symbol: 'HYPE',
    explorerUrl: 'https://hyperevmscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_hyperliquid.jpg',
    nativeCurrency: { name: 'Hyperliquid', symbol: 'HYPE', decimals: 18 },
  },
  {
    id: 'immutable-zkevm',
    name: 'Immutable zkEVM',
    chainId: 13371,
    rpcUrl: 'https://rpc.immutable.com',
    symbol: 'IMX',
    explorerUrl: 'https://explorer.immutable.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_immutable%20zkevm.jpg',
    nativeCurrency: { name: 'Immutable X', symbol: 'IMX', decimals: 18 },
  },
  {
    id: 'ink',
    name: 'Ink',
    chainId: 57073,
    rpcUrl: 'https://rpc-gel.inkonchain.com',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.inkonchain.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_ink.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'iotex',
    name: 'IoTeX',
    chainId: 4689,
    rpcUrl: 'https://babel-api.mainnet.iotex.io',
    symbol: 'IOTX',
    explorerUrl: 'https://iotexscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_iotex.jpg',
    nativeCurrency: { name: 'IoTeX', symbol: 'IOTX', decimals: 18 },
  },
  {
    id: 'kaia',
    name: 'Kaia',
    chainId: 8217,
    rpcUrl: 'https://public-en.node.kaia.io',
    symbol: 'KAIA',
    explorerUrl: 'https://kaiascan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_kaia.jpg',
    nativeCurrency: { name: 'Kaia', symbol: 'KAIA', decimals: 18 },
  },
  {
    id: 'katana',
    name: 'Katana',
    chainId: 747474,
    rpcUrl: 'https://rpc.katana.network',
    symbol: 'ETH',
    explorerUrl: 'https://katanascan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_katana.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'kava',
    name: 'Kava',
    chainId: 2222,
    rpcUrl: 'https://evm.kava.io',
    symbol: 'KAVA',
    explorerUrl: 'https://kavascan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_kava.jpg',
    nativeCurrency: { name: 'Kava', symbol: 'KAVA', decimals: 18 },
  },
  {
    id: 'kiteai',
    name: 'KiteAI',
    chainId: 2366,
    rpcUrl: 'https://rpc.gokite.ai',
    symbol: 'KITE',
    explorerUrl: 'https://kitescan.ai',
    type: 'EVM',
    nativeCurrency: { name: 'Kite', symbol: 'KITE', decimals: 18 },
  },
  {
    id: 'lens',
    name: 'Lens',
    chainId: 232,
    rpcUrl: 'https://rpc.lens.xyz',
    symbol: 'GHO',
    explorerUrl: 'https://explorer.lens.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_lens.jpg',
    nativeCurrency: { name: 'GHO', symbol: 'GHO', decimals: 18 },
  },
  {
    id: 'linea',
    name: 'Linea',
    chainId: 59144,
    rpcUrl: 'https://rpc.linea.build',
    symbol: 'ETH',
    explorerUrl: 'https://lineascan.build',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_linea.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'lisk',
    name: 'Lisk',
    chainId: 1135,
    rpcUrl: 'https://rpc.api.lisk.com',
    symbol: 'ETH',
    explorerUrl: 'https://blockscout.lisk.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_lisk.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'manta-pacific',
    name: 'Manta Pacific',
    chainId: 169,
    rpcUrl: 'https://pacific-rpc.manta.network/http',
    symbol: 'ETH',
    explorerUrl: 'https://pacific-explorer.manta.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_manta.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'mantle',
    name: 'Mantle',
    chainId: 5000,
    rpcUrl: 'https://rpc.mantle.xyz',
    symbol: 'MNT',
    explorerUrl: 'https://mantlescan.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_mantle.jpg',
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
  },
  {
    id: 'megaeth',
    name: 'MegaETH',
    chainId: 4326,
    rpcUrl: 'https://mainnet.megaeth.com/rpc',
    symbol: 'ETH',
    explorerUrl: 'https://mega.etherscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_megaeth.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'merlin',
    name: 'Merlin',
    chainId: 4200,
    rpcUrl: 'https://rpc.merlinchain.io',
    symbol: 'BTC',
    explorerUrl: 'https://scan.merlinchain.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_merlin.jpg',
    nativeCurrency: { name: 'Bitcoin', symbol: 'BTC', decimals: 18 },
  },
  {
    id: 'metis',
    name: 'Metis',
    chainId: 1088,
    rpcUrl: 'https://andromeda.metis.io/?owner=1088',
    symbol: 'METIS',
    explorerUrl: 'https://explorer.metis.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_metis.jpg',
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
  },
  {
    id: 'mitosis',
    name: 'Mitosis',
    chainId: 124816,
    rpcUrl: 'https://rpc.mitosis.org',
    symbol: 'MITO',
    explorerUrl: 'https://scan.mitosis.org',
    type: 'EVM',
    nativeCurrency: { name: 'Mitosis', symbol: 'MITO', decimals: 18 },
  },
  {
    id: 'mode',
    name: 'Mode',
    chainId: 34443,
    rpcUrl: 'https://mainnet.mode.network',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.mode.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_mode.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'monad',
    name: 'Monad',
    chainId: 143,
    rpcUrl: 'https://rpc.monad.xyz',
    symbol: 'MON',
    explorerUrl: 'https://monadexplorer.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_monad.jpg',
    nativeCurrency: { name: 'Monad', symbol: 'MON', decimals: 18 },
  },
  {
    id: 'moonbeam',
    name: 'Moonbeam',
    chainId: 1284,
    rpcUrl: 'https://rpc.api.moonbeam.network',
    symbol: 'GLMR',
    explorerUrl: 'https://moonbeam.moonscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_moonbeam.jpg',
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
  },
  {
    id: 'moonriver',
    name: 'Moonriver',
    chainId: 1285,
    rpcUrl: 'https://rpc.api.moonriver.moonbeam.network',
    symbol: 'MOVR',
    explorerUrl: 'https://moonriver.moonscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_moonriver.jpg',
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18 },
  },
  {
    id: 'morph',
    name: 'Morph',
    chainId: 2818,
    rpcUrl: 'https://rpc.morphl2.io',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.morphl2.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_morph.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'oasys',
    name: 'Oasys',
    chainId: 248,
    rpcUrl: 'https://rpc.mainnet.oasys.games',
    symbol: 'OAS',
    explorerUrl: 'https://explorer.oasys.games',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_oasys.jpg',
    nativeCurrency: { name: 'Oasys', symbol: 'OAS', decimals: 18 },
  },
  {
    id: 'opbnb',
    name: 'opBNB',
    chainId: 204,
    rpcUrl: 'https://opbnb-mainnet-rpc.bnbchain.org',
    symbol: 'BNB',
    explorerUrl: 'https://mainnet.opbnbscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_op_bnb.jpg',
    nativeCurrency: { name: 'Binance Coin', symbol: 'BNB', decimals: 18 },
  },
  {
    id: 'orderly',
    name: 'Orderly',
    chainId: 291,
    rpcUrl: 'https://rpc.orderly.network',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.orderly.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_orderly.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'plasma',
    name: 'Plasma',
    chainId: 9745,
    rpcUrl: 'https://rpc.plasma.to',
    symbol: 'XPL',
    explorerUrl: 'https://plasmascan.to',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_plasma.jpg',
    nativeCurrency: { name: 'Plasma', symbol: 'XPL', decimals: 18 },
  },
  {
    id: 'plume',
    name: 'Plume',
    chainId: 98866,
    rpcUrl: 'https://rpc.plume.org',
    symbol: 'PLUME',
    explorerUrl: 'https://explorer.plume.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_plume%20mainnet.jpg',
    nativeCurrency: { name: 'Plume', symbol: 'PLUME', decimals: 18 },
  },
  {
    id: 'reya',
    name: 'Reya',
    chainId: 1729,
    rpcUrl: 'https://rpc.reya.network',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.reya.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_reya.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'robinhood',
    name: 'Robinhood',
    chainId: 4663,
    rpcUrl: 'https://rpc.mainnet.chain.robinhood.com',
    symbol: 'ETH',
    explorerUrl: 'https://robinhoodchain.blockscout.com',
    type: 'EVM',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'ronin',
    name: 'Ronin',
    chainId: 2020,
    rpcUrl: 'https://api.roninchain.com/rpc',
    symbol: 'RON',
    explorerUrl: 'https://app.roninchain.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_ronin.jpg',
    nativeCurrency: { name: 'Ronin', symbol: 'RON', decimals: 18 },
  },
  {
    id: 'rootstock',
    name: 'Rootstock',
    chainId: 30,
    rpcUrl: 'https://public-node.rsk.co',
    symbol: 'RBTC',
    explorerUrl: 'https://explorer.rootstock.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_rootstock.jpg',
    nativeCurrency: { name: 'Rootstock BTC', symbol: 'RBTC', decimals: 18 },
  },
  {
    id: 'scroll',
    name: 'Scroll',
    chainId: 534352,
    rpcUrl: 'https://rpc.scroll.io',
    symbol: 'ETH',
    explorerUrl: 'https://scrollscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_scroll.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'sei',
    name: 'Sei',
    chainId: 1329,
    rpcUrl: 'https://evm-rpc.sei-apis.com',
    symbol: 'SEI',
    explorerUrl: 'https://seitrace.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_sei.jpg',
    nativeCurrency: { name: 'Sei', symbol: 'SEI', decimals: 18 },
  },
  {
    id: 'soneium',
    name: 'Soneium',
    chainId: 1868,
    rpcUrl: 'https://rpc.soneium.org',
    symbol: 'ETH',
    explorerUrl: 'https://soneium.blockscout.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_soneium.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'sonic',
    name: 'Sonic',
    chainId: 146,
    rpcUrl: 'https://rpc.soniclabs.com',
    symbol: 'S',
    explorerUrl: 'https://sonicscan.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_sonic.jpg',
    nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 18 },
  },
  {
    id: 'sophon',
    name: 'Sophon',
    chainId: 50104,
    rpcUrl: 'https://rpc.sophon.xyz',
    symbol: 'SOPH',
    explorerUrl: 'https://explorer.sophon.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_sophon.jpg',
    nativeCurrency: { name: 'Sophon', symbol: 'SOPH', decimals: 18 },
  },
  {
    id: 'stable',
    name: 'Stable',
    chainId: 988,
    rpcUrl: 'https://rpc.stable.xyz',
    symbol: 'USDT0',
    explorerUrl: 'https://stablescan.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_stable.jpg',
    nativeCurrency: { name: 'USDT0', symbol: 'USDT0', decimals: 18 },
  },
  {
    id: 'tac',
    name: 'TAC',
    chainId: 239,
    rpcUrl: 'https://rpc.tac.build',
    symbol: 'TAC',
    explorerUrl: 'https://explorer.tac.build',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_tac.jpg',
    nativeCurrency: { name: 'TAC', symbol: 'TAC', decimals: 18 },
  },
  {
    id: 'taiko',
    name: 'Taiko',
    chainId: 167000,
    rpcUrl: 'https://rpc.mainnet.taiko.xyz',
    symbol: 'ETH',
    explorerUrl: 'https://taikoscan.io',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_taiko.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'tempo',
    name: 'Tempo',
    chainId: 4217,
    rpcUrl: 'https://rpc.mainnet.tempo.xyz',
    symbol: 'USD',
    explorerUrl: 'https://explore.tempo.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_tempo.jpg',
    nativeCurrency: { name: 'USD', symbol: 'USD', decimals: 18 },
  },
  {
    id: 'unichain',
    name: 'Unichain',
    chainId: 130,
    rpcUrl: 'https://mainnet.unichain.org',
    symbol: 'ETH',
    explorerUrl: 'https://uniscan.xyz',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_unichain.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'wemix',
    name: 'WEMIX',
    chainId: 1111,
    rpcUrl: 'https://api.wemix.com',
    symbol: 'WEMIX',
    explorerUrl: 'https://wemixscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_wemix3.0.jpg',
    nativeCurrency: { name: 'WEMIX', symbol: 'WEMIX', decimals: 18 },
  },
  {
    id: 'world-chain',
    name: 'World Chain',
    chainId: 480,
    rpcUrl: 'https://worldchain-mainnet.g.alchemy.com/public',
    symbol: 'ETH',
    explorerUrl: 'https://worldscan.org',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_world%20chain.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'x-layer',
    name: 'X Layer',
    chainId: 196,
    rpcUrl: 'https://rpc.xlayer.tech',
    symbol: 'OKB',
    explorerUrl: 'https://www.oklink.com/xlayer',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_x-layer.jpg',
    nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
  },
  {
    id: 'xdc',
    name: 'XDC',
    chainId: 50,
    rpcUrl: 'https://rpc.xdc.org',
    symbol: 'XDC',
    explorerUrl: 'https://xdcscan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_xdc.jpg',
    nativeCurrency: { name: 'XDC', symbol: 'XDC', decimals: 18 },
  },
  {
    id: 'zetachain',
    name: 'ZetaChain',
    chainId: 7000,
    rpcUrl: 'https://zetachain-evm.blockpi.network/v1/rpc/public',
    symbol: 'ZETA',
    explorerUrl: 'https://zetascan.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_zetachain.jpg',
    nativeCurrency: { name: 'Zeta', symbol: 'ZETA', decimals: 18 },
  },
  {
    id: 'zircuit',
    name: 'Zircuit',
    chainId: 48900,
    rpcUrl: 'https://mainnet.zircuit.com',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.zircuit.com',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_zircuit.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'zksync-era',
    name: 'zkSync Era',
    chainId: 324,
    rpcUrl: 'https://mainnet.era.zksync.io',
    symbol: 'ETH',
    explorerUrl: 'https://era.zksync.network',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_zksync%20era.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
  {
    id: 'zora',
    name: 'Zora',
    chainId: 7777777,
    rpcUrl: 'https://rpc.zora.energy',
    symbol: 'ETH',
    explorerUrl: 'https://explorer.zora.energy',
    type: 'EVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_zora.jpg',
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
  },
]

export const SVM_NETWORKS: Network[] = [
  {
    id: 'solana-mainnet',
    name: 'Solana Mainnet',
    chainId: 'mainnet-beta',
    rpcUrl: `https://mainnet.helius-rpc.com/?api-key=${ENV_HELIUS_KEY}`,
    alchemyRpcUrl: alchemyUrl('solana-mainnet'),
    symbol: 'SOL',
    explorerUrl: 'https://explorer.solana.com',
    type: 'SVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_solana.jpg',
    nativeCurrency: {
      name: 'Solana',
      symbol: 'SOL',
      decimals: 9,
    },
  },
  {
    id: 'solana-devnet',
    name: 'Solana Devnet',
    chainId: 'devnet',
    rpcUrl: clusterApiUrl('devnet'),
    alchemyRpcUrl: alchemyUrl('solana-devnet'),
    symbol: 'SOL',
    explorerUrl: 'https://explorer.solana.com?cluster=devnet',
    type: 'SVM',
    logoURI: 'https://icons.llamao.fi/icons/chains/rsz_solana.jpg',
    nativeCurrency: {
      name: 'Solana',
      symbol: 'SOL',
      decimals: 9,
    },
  },
]

export const ALL_NETWORKS = [...EVM_NETWORKS, ...SVM_NETWORKS]

const NETWORK_LOGO_BY_ID: Record<string, string> = Object.fromEntries(
  ALL_NETWORKS.filter((n) => n.logoURI).map((n) => [n.id, n.logoURI!]),
)
const NETWORK_NAME_BY_ID: Record<string, string> = Object.fromEntries(
  ALL_NETWORKS.map((n) => [n.id, n.name]),
)

/** Resolve a network's remote logo URL (DefiLlama CDN) by network id, if any. */
export function getNetworkLogo(networkId: string): string | undefined {
  return NETWORK_LOGO_BY_ID[networkId]
}

/** Resolve a network's display name by id (for icon fallback avatars). */
export function getNetworkName(networkId: string): string | undefined {
  return NETWORK_NAME_BY_ID[networkId]
}

export function getNetworksByType(type: 'EVM' | 'SVM'): Network[] {
  return type === 'EVM' ? EVM_NETWORKS : SVM_NETWORKS
}

export function getDefaultNetworkId(type: 'EVM' | 'SVM'): string {
  return type === 'EVM' ? 'ethereum' : 'solana-mainnet'
}

export function findNetworkById(id: string): Network | undefined {
  return ALL_NETWORKS.find((n) => n.id === id)
}

export function findNetworkByResearchId(researchId: string): Network | undefined {
  return findNetworkById(researchId) || findNetworkById(`${researchId}-mainnet`)
}

export function getExplorerUrl(researchNetworkId: string): string {
  return findNetworkByResearchId(researchNetworkId)?.explorerUrl || ''
}

export function getChainId(researchNetworkId: string): number {
  const chainId = findNetworkByResearchId(researchNetworkId)?.chainId
  return typeof chainId === 'number' ? chainId : 0
}

export function getNativeSymbol(researchNetworkId: string): string {
  return findNetworkByResearchId(researchNetworkId)?.symbol || 'ETH'
}

export function getChainType(researchNetworkId: string): 'EVM' | 'SVM' {
  return findNetworkByResearchId(researchNetworkId)?.type || 'EVM'
}

const NATIVE_TOKEN_ADDRESSES: Record<string, string> = {
  base: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  ethereum: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  arbitrum: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  optimism: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  solana: 'So11111111111111111111111111111111111111112',
}

const NATIVE_PRICE_FALLBACKS: Record<string, number> = {
  base: 2300,
  ethereum: 2300,
  arbitrum: 2300,
  optimism: 2300,
  solana: 150,
}

export function getNativeTokenAddress(researchNetworkId: string): string {
  return NATIVE_TOKEN_ADDRESSES[researchNetworkId] || NATIVE_TOKEN_ADDRESSES.ethereum
}

export function getNativePriceFallback(researchNetworkId: string): number {
  return NATIVE_PRICE_FALLBACKS[researchNetworkId] || 2300
}

export function isValidAddress(address: string): boolean {
  if (address.startsWith('0x') && address.length === 42) {
    return /^0x[a-fA-F0-9]{40}$/.test(address)
  }
  if (!address.startsWith('0x') && address.length >= 32 && address.length <= 44) {
    return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address)
  }
  return false
}

export function detectNetworkFromAddress(address: string): string {
  if (!address.startsWith('0x') && address.length >= 32 && address.length <= 44) {
    return 'solana'
  }
  return 'base'
}